# Generated by Django 3.2.6 on 2021-08-09 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0005_auto_20210809_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='activity',
        ),
        migrations.AddField(
            model_name='submission',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kanvas_app.activity'),
            preserve_default=False,
        ),
    ]
