# Generated by Django 3.2.6 on 2021-08-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas_app', '0007_alter_submission_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='points',
            field=models.IntegerField(),
        ),
    ]
